version: '3'

services:
  database-mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=<db-root-pw>
    - MYSQL_DATABASE=minecraft
    - MYSQL_USER=minecraft
    - MYSQL_PASSWORD=<db-user-pw>

  database-mongo:
    image: frodenas/mongodb:3.0
    environment:
    - MONGODB_DBNAME=cubeengine
    - MONGODB_USERNAME=minecraft
    - MONGODB_PASSWORD=<mongo-db-user-pw>

  forge:
    image: cubeengine/forge:latest
    depends_on:
    - database-mysql
    - database-mongo
    volumes:
    - ./data/config:/opt/minecraft/config
    - ./data/mods:/opt/minecraft/mods
    environment:
    - DB_HOST=database-mysql
    - DB_PASSWORD=<db-user-pw>
    - MONGO_DB_HOST=database-mongo
    - MONGO_DB_PASSWORD=<mongo-db-user-pw>
    - JAVA_VM_ARGS=-Xmx1G
